export const ORDER_CREATE_REQ = 'ORDER_CREATE_REQ'
export const ORDER_CREATE_SUC = 'ORDER_CREATE_SUC'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_RESET = 'ORDER_RESET'

export const  ORDER_DETAIL_REQ = 'ORDER_DETAIL_REQ'
export const  ORDER_DETAIL_SUC = 'ORDER_DETAIL_SUC'
export const  ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'

export const  ORDER_LIST_USER_SUC = 'ORDER_LIST_USER_SUC'
export const  ORDER_LIST_USER_FAIL = 'ORDER_LIST_USER_FAIL'
export const  ORDER_LIST_USER_REQ = 'ORDER_LIST_USER_REQ'
export const  ORDER_LIST_USER_RESET = 'ORDER_BY_USER_RESET'

export const  ORDER_LIST_SUC = 'ORDER_LIST_SUC'
export const  ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'
export const  ORDER_LIST_REQ = 'ORDER_LIST_REQ'
export const  ORDER_LIST_RESET = 'ORDER_BY_RESET'

export const  ORDER_DELIVERY_SUC = 'ORDER_DELIVERY_SUC'
export const  ORDER_DELIVERY_FAIL = 'ORDER_DELIVERY_FAIL'
export const  ORDER_DELIVERY_REQ = 'ORDER_DELIVERY_REQ'
export const  ORDER_DELIVERY_RESET= 'ORDER_DELIVERY_RESET'

export const  ORDER_PAY_SUC = 'ORDER_PAY_SUC'
export const  ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const  ORDER_PAY_REQ = 'ORDER_PAY_REQ'
export const  ORDER_PAY_RESET = 'ORDER_PAY_RESET'



