export const ORDER_CREATE_REQ = 'ORDER_CREATE_REQ'
export const ORDER_CREATE_SUC = 'ORDER_CREATE_SUC'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_RESET = 'ORDER_RESET'

export const  ORDER_DETAIL_REQ = 'ORDER_DETAIL_REQ'
export const  ORDER_DETAIL_SUC = 'ORDER_DETAIL_SUC'
export const  ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'

export const  ORDER_LIST_USER_SUC = 'ORDER_LIST_USER_SUC'
export const  ORDER_LIST_USER_FAIL = 'ORDER_LIST_USER_FAIL'
export const  ORDER_LIST_USER_REQ = 'ORDER_LIST_USER_REQ'
export const  ORDER_LIST_USER_RESET = 'ORDER_BY_USER_RESET'

