export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST'
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS'
export const PRODUCT_FAIL = 'PRODUCT_FAIL'


export const PRODUCT_DELETE_REQ = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUC = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQ = 'PRODUCT_CREATE_REQ'
export const PRODUCT_CREATE_SUC = 'PRODUCT_CREATE_SUC'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_EDIT_REQ = 'PRODUCT_EDIT_REQ'
export const PRODUCT_EDIT_SUC = 'PRODUCT_EDIT_SUC'
export const PRODUCT_EDIT_FAIL = 'PRODUCT_EDIT_FAIL'
export const PRODUCT_EDIT_RESET = 'PRODUCT_EDIT_RESET'



