export const USER_LOGIN_REQ = 'USER_LOGIN_REQ'
export const USER_LOGIN_SUC = 'USER_LOGIN_SUC'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQ = 'USER_REGISTER_REQ'
export const USER_REGISTER_SUC = 'USER_REGISTER_SUC'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_PROFILE_REQ = 'USER_PROFILE_REQ'
export const USER_PROFILE_SUC = 'USER_PROFILE_SUC'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USER_PROFILE_CHANGE_REQ = 'USER_PROFILE_CHANGE_REQ'
export const USER_PROFILE_CHANGE_SUC = 'USER_PROFILE_CHANGE_SUC'
export const USER_PROFILE_CHANGE_FAIL = 'USER_PROFILE_CHANGE_FAIL'
export const USER_PROFILE_CHANGE_RESET = 'USER_PROFILE_CHANGE_RESET'

export const USER_LIST_REQ = 'USER_LIST_REQ'
export const USER_LIST_SUC = 'USER_LIST_SUC'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQ = 'USER_DELETE_REQ'
export const USER_DELETE_SUC = 'USER_DELETE_SUC'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_PROFILE_VIEW_BY_ID_REQ = 'USER_PROFILE_VIEW_REQ'
export const USER_PROFILE_VIEW_BY_ID_SUC = 'USER_PROFILE_VIEW_SUC'
export const USER_PROFILE_VIEW_BY_ID_FAIL = 'USER_PROFILE_VIEW_FAIL'

export const USER_UPDATE_REQ = 'USER_UPDATE_REQ'
export const USER_UPDATE_SUC = 'USER_UPDATE_SUC'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'
