# Generated by Django 4.0.3 on 2022-04-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
