# Generated by Django 4.0.3 on 2022-04-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_order_contanctinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contanctInfo',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='contanctInfo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
