# Generated by Django 4.0.3 on 2022-04-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_order_contanctinfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='contanctInfo',
            new_name='contactInfo',
        ),
    ]
